config_version = 13

[general]
show_changelog_on_startup = false

[bar.default]
end = [ "tray", "brightness", "volume", "battery", "network", "control-center", "session" ]
font_family = "JetBrainsMono NF"
widget_spacing = 15
margin_ends = 0
radius = 0

[notification]
filter_order = [ "filter" ]

    [notification.filter.filter]
    allow_permanent = false
    allowed_urgencies = [ "critical" ]
    bypass_dnd = false
    enabled = true
    match = "netbird"
    play_sound = false
    save_history = false
    show_toast = false

    [notification.filter.filter-2]
    allow_permanent = true
    bypass_dnd = false
    enabled = true
    match = "noctalia"
    match_content = "^.*output-scale.*$"
    override_duration = 1000
    play_sound = true
    save_history = true
    show_toast = true

[osd.kinds]
lock_keys = false
media = false

[shell]
font_family = "JetBrainsMono NF"

    [shell.animation]
    speed = 4.0

[theme]
builtin = "Gruvbox"
mode = "dark"
source = "builtin"

[widget.clock]
format = "{:%I:%M %p}"

[widget.control-center]
enabled = false
glyph = "snowflake"

[widget.launcher]
enabled = false

[widget.wallpaper]
enabled = false

[widget.network]
show_label = false
