keys:
  - &padrick age1jmwmvkcn59ja8534h47hzq23uyf6wsjef532px626tmmp36hmy3qp666tw
  - &jobert age1y7k3sgnvhlxz0lctllgradx4ng4ky24lmwhr7tnz4py9fv7c5vhqcufyyh

creation_rules:
  - path_regex: secrets/system/.*\.yaml$
    key_groups:
      - age:
          - *padrick
          - *jobert
  - path_regex: secrets/hosts/padrick/.*\.yaml$
    key_groups:
      - age:
          - *padrick
  - path_regex: secrets/hosts/jobert/.*\.yaml$
    key_groups:
      - age:
          - *jobert
