# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "ehci_pci"
    "xhci_pci_renesas"
    "xhci_pci"
    "usb_storage"
    "sd_mod"
    "rtsx_pci_sdmmc"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/luks-b3de44df-5f22-42ec-bb0b-87147a44830c";
    fsType = "btrfs";
    options = [
      "subvol=root"
      "compress=zstd"
      "noatime"
      "ssd"
      "discard=async"
    ];
  };

  boot.initrd.luks.devices."luks-b3de44df-5f22-42ec-bb0b-87147a44830c" = {
    device = "/dev/disk/by-uuid/b3de44df-5f22-42ec-bb0b-87147a44830c";
    allowDiscards = true;
  };

  fileSystems."/home" = {
    device = "/dev/mapper/luks-b3de44df-5f22-42ec-bb0b-87147a44830c";
    fsType = "btrfs";
    options = [
      "subvol=home"
      "compress=zstd"
      "noatime"
      "ssd"
      "discard=async"
    ];
  };

  fileSystems."/nix" = {
    device = "/dev/mapper/luks-b3de44df-5f22-42ec-bb0b-87147a44830c";
    fsType = "btrfs";
    options = [
      "subvol=nix"
      "compress=zstd"
      "noatime"
      "ssd"
      "discard=async"
      "nodatacow"
    ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/C90D-06DF";
    fsType = "vfat";
    options = [
      "fmask=0177"
      "dmask=0077"
      "noexec"
      "nosuid"
      "nodev"
    ];
  };

  fileSystems."/swap" = {
    device = "/dev/mapper/luks-b3de44df-5f22-42ec-bb0b-87147a44830c";
    fsType = "btrfs";
    options = [
      "subvol=swap"
      "noatime"
      "ssd"
      "discard=async"
    ];
  };

  swapDevices = [
    { device = "/swap/swapfile"; }
  ];

  boot.initrd.systemd.enable = true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
