# Generated by `nixos-generate-config`; verify before regenerating.
{
  flake.modules.nixos.padrick-hardware =
    {
      config,
      lib,
      modulesPath,
      ...
    }:

    {
      imports = [
        (modulesPath + "/installer/scan/not-detected.nix")
      ];

      boot = {
        initrd.availableKernelModules = [
          "nvme"
          "ehci_pci"
          "xhci_pci_renesas"
          "xhci_pci"
          "usb_storage"
          "sd_mod"
          "rtsx_pci_sdmmc"
        ];
        initrd.kernelModules = [ ];
        kernelModules = [ "kvm-amd" ];
        extraModulePackages = [ ];
      };

      nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
      hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
    };
}
