#!/usr/bin/env bash

SOURCE="@DEFAULT_AUDIO_SOURCE@"
LED="/sys/class/leds/platform::micmute/brightness"

wpctl set-mute "$SOURCE" toggle

if wpctl get-volume "$SOURCE" | grep -q MUTED; then
    echo 1 > "$LED"
else
    echo 0 > "$LED"
fi
