set -g default-terminal "screen-256color"

# set -g prefix C-a
# unbind C-b
# bind-key C-a send-prefix

unbind %
bind | split-window -h

unbind '"'
bind - split-window -v

unbind r
bind r source-file ~/.tmux.conf

bind -r m resize-pane -Z
bind q killp

set -g mouse on

set -g @plugin 'tmux-plugins/tpm'

# plugins
# set -g @plugin 'christoomey/vim-tmux-navigator'

run '~/.tmux/plugins/tpm/tpm'

# tmux cheatsheet
# * prefix d
#     detach from session
# * prefix $
#     rename session
# * prefix ( or )
#     go to next/prev session
# * prefix r
#     refresh tmux conf
# * prefix I
#     load plugins?
# * prefix c
#     create new window
# * prefix q
#     delete window
# * prefix n/p
#     go to next/prev window
# * prefix n
#     go to nth window
# * prefix ,
#     rename window
# * prefix s
#     see all sessions
# * prefix w
#     see all windows
# * prefix |
#     open horizontal split pane
# * prefix -
#     open vertical split pane
# * prefix arrows
#     go to pane
# * ctrl hjkl
#     go to pane
